// <auto-generated />
namespace GarbageCollection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alteredpickupday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alteredpickupday));
        
        string IMigrationMetadata.Id
        {
            get { return "201709132100424_altered pickup day"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
